config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/indexex'
 
  root 'home#index'

  get 'home/index'
  resources :authors, only: [:index]
  resources :sales
  resources :reviews
  resources :books
  resources :authors

  get 'author_stats', to: 'author_stats#index'
  get 'top_books', to: 'top_books#index'
  get 'top_selling_books', to: 'top_selling_books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/author.rb
class Author < ApplicationRecord
 
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :books
  has_one_attached :profile_image

  def total_sales
      books.sum(:number_of_sales)
    end



  settings do
    mappings dynamic: false do
      indexes :name, type: :text
      indexes :country_of_origin, type: :text
      indexes :description, type: :text
    end
  end

  def as_indexed_json(options = {})
    {
      name: name,
      country_of_origin: country_of_origin,
      description: description
    }
  end

  def self.search(query)
    if query.present?
      __elasticsearch__.search(
        {
          query: {
            multi_match: {
              query: query,
              fields: ['name^2', 'country_of_origin', 'description']
            }
          }
        }
      ).records
    else
      all
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.search(params[:query]).page(params[:page])
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_author
      @author = Author.find(params[:id])
    end

    def author_params
      params.require(:author).permit(:name, :date_of_birth, :country_of_origin, :description, :profile_image)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Image :</strong>
    <% if author.profile_image.attached? %>
      <%= image_tag author.profile_image %>
    <% else %>
      <p>No image available</p>
    <% end %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= author.date_of_birth %>
  </p>

  <p>
    <strong>Country of origin:</strong>
    <%= author.country_of_origin %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= author.description %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :profile_image, "Author Imaged", style: "display: block" %>
    <%= form.file_field :profile_image %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :date_of_birth, style: "display: block" %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div>
    <%= form.label :country_of_origin, style: "display: block" %>
    <%= form.text_field :country_of_origin %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>
<%= link_to "New author", new_author_path %>


<%= form_with url: authors_path, method: :get, local: true do %>
  <%= label_tag :query, "Search for authors:" %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search" %>
<% end %>


<h2>Search Results</h2>
<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>