config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  get 'search/indexex'
 
  root 'home#index'

  get 'home/index'
  resources :authors, only: [:index]
  resources :sales
  resources :reviews
  resources :books
  resources :authors

  get 'author_stats', to: 'author_stats#index'
  get 'top_books', to: 'top_books#index'
  get 'top_selling_books', to: 'top_selling_books#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookman</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Add Bootstrap CSS for styling -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Bookman</a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Books', books_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Authors', authors_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sales', sales_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reviews', reviews_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Top Scores', top_books_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Top Selling', top_selling_books_path, class: 'nav-link' %>
        </li>
      <li class="nav-item">
        <%= link_to 'Author Stats', author_stats_path, class: 'nav-link' %>
      </li>
      </ul>
    </div>
  </nav>

  <div class="container mt-4">
    <%= yield %>
  </div>

  <!-- Add Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>